=== sydrawat01/INFO7255/src/api/utils/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "INFO-7255 JSON Schema",
  "description": "JSON Schema for medical use case",
  "type": "object",
  "properties": {
    "planCostShares": {
      "type": "object",
      "properties": {
        "deductible": {
          "type": "number"
        },
        "_org": {
          "type": "string"
        },
        "copay": {
          "type": "number"
        },
        "objectId": {
          "type": "string"
        },
        "objectType": {
          "type": "string"
        }
      },
      "required": [
        "deductible",
        "_org",
        "copay",
        "objectId",
        "objectType"
      ],
      "additionalProperties": false
    },
    "linkedPlanServices": {
      "type": "array",
      "minItems": 1,
      "items": [
        {
          "type": "object",
          "properties": {
            "linkedService": {
              "type": "object",
              "properties": {
                "_org": {
                  "type": "string"
                },
                "objectId": {
                  "type": "string"
                },
                "objectType": {
                  "type": "string"
                },
                "name": {
                  "type": "string"
                }
              },
              "required": [
                "_org",
                "objectId",
                "objectType",
                "name"
              ],
              "additionalProperties": false
            },
            "planserviceCostShares": {
              "type": "object",
              "properties": {
                "deductible": {
                  "type": "number"
                },
                "_org": {
                  "type": "string"
                },
                "copay": {
                  "type": "number"
                },
                "objectId": {
                  "type": "string"
                },
                "objectType": {
                  "type": "string"
                }
              },
              "required": [
                "deductible",
                "_org",
                "copay",
                "objectId",
                "objectType"
              ],
              "additionalProperties": false
            },
            "_org": {
              "type": "string"
            },
            "objectId": {
              "type": "string"
            },
            "objectType": {
              "type": "string"
            }
          },
          "required": [
            "linkedService",
            "planserviceCostShares",
            "_org",
            "objectId",
            "objectType"
          ],
          "additionalProperties": false
        }
      ]
    },
    "_org": {
      "type": "string"
    },
    "objectId": {
      "type": "string"
    },
    "objectType": {
      "type": "string"
    },
    "planType": {
      "type": "string"
    },
    "creationDate": {
      "type": "string"
    }
  },
  "required": [
    "planCostShares",
    "linkedPlanServices",
    "_org",
    "objectId",
    "objectType",
    "planType",
    "creationDate"
  ],
  "additionalProperties": false
}

=== sydrawat01/INFO7255/static/plan.patch.json
{
	"planCostShares": {
			"deductible": 2000,
			"_org": "example.com",
			"copay": 23,
			"objectId": "1234vxc2324sdf-501",
			"objectType": "membercostshare"
	},
	"linkedPlanServices": [{
	"linkedService": {
		"_org": "example.com",
		"objectId": "1234520xvc30sfs-505abc",
		"objectType": "service",
		"name": "well baby"
	},
	"planserviceCostShares": {
		"deductible": 10,
		"_org": "example.com",
		"copay": 175,
		"objectId": "1234512xvc1314sdfsd-506abc",
		"objectType": "membercostshare"
	},
	"_org": "example.com",
	"objectId": "27283xvx9sdf-507abc",
	"objectType": "planservice"
}],

"_org": "example.com",
"objectId": "12xvxc345ssdsds-508",
"objectType": "plan",
"planType": "inNetwork",
"creationDate": "12-12-2017"
}

=== sydrawat01/INFO7255/use_case.json
{
	"planCostShares": {
		"deductible": 2000,
		"_org": "example.com",
		"copay": 23,
		"objectId": "1234vxc2324sdf-501",
		"objectType": "membercostshare"

	},
	"linkedPlanServices": [{
		"linkedService": {
			"_org": "example.com",
			"objectId": "1234520xvc30asdf-502",
			"objectType": "service",
			"name": "Yearly physical"
		},
		"planserviceCostShares": {
			"deductible": 10,
			"_org": "example.com",
			"copay": 0,
			"objectId": "1234512xvc1314asdfs-503",
			"objectType": "membercostshare"
		},
		"_org": "example.com",
		"objectId": "27283xvx9asdff-504",
		"objectType": "planservice"
	}, {
		"linkedService": {
			"_org": "example.com",
			"objectId": "1234520xvc30sfs-505",
			"objectType": "service",
			"name": "well baby"
		},
		"planserviceCostShares": {
			"deductible": 10,
			"_org": "example.com",
			"copay": 175,
			"objectId": "1234512xvc1314sdfsd-506",
			"objectType": "membercostshare"
		},

		"_org": "example.com",

		"objectId": "27283xvx9sdf-507",
		"objectType": "planservice"
	}],


	"_org": "example.com",
	"objectId": "12xvxc345ssdsds-508",
	"objectType": "plan",
	"planType": "inNetwork",
	"creationDate": "12-12-2017"
}
